server:
  port: 9000

#指定注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#服务的名称
spring:
  application:
    name: api-gateway

#自定义路由映射
zuul:
  routes:
    order-service: /apigateway/order/**
    product-service: /apigateway/product/**
  ignored-patterns: /*-service/**
  #处理http请求头为空的问题
  sensitive-headers:
